// Auto-generated by expo-ondevice-ai config plugin
// This file is compiled with C++ interop enabled, isolated from React Native headers.

import Foundation
import Locanara
import LocalLLMClient
import LocalLLMClientLlama
import os.log
#if os(iOS)
import UIKit
#endif

private let logger = Logger(subsystem: "com.locanara.bridge", category: "LlamaCppBridge")

// MARK: - Bridge Engine (InferenceEngine conformance)

@available(iOS 17.0, *)
final class BridgedLlamaCppEngine: @unchecked Sendable, InferenceEngine, LlamaCppEngineProtocol {

    static var engineType: InferenceEngineType { .llamaCpp }
    var engineName: String { "On-Device LLM (llama.cpp via bridge)" }
    var isLoaded: Bool { lock.withLock { loaded } }
    var isMultimodal: Bool { mmprojPath != nil }

    private var llmSession: LLMSession?
    private let modelPath: URL
    private let mmprojPath: URL?
    private var isCancelled = false
    private var isInferencing = false
    private var loaded = false
    private let lock = NSLock()

    init(modelPath: URL, mmprojPath: URL?) {
        self.modelPath = modelPath
        self.mmprojPath = mmprojPath
    }

    private func loadedSessionSnapshot() -> LLMSession? {
        lock.withLock { loaded ? llmSession : nil }
    }

    private func beginInference() async throws {
        while lock.withLock({ isInferencing }) {
            try await Task.sleep(nanoseconds: 100_000_000)
        }
        lock.withLock {
            isInferencing = true
            isCancelled = false
        }
    }

    private func endInference() {
        lock.withLock { isInferencing = false }
    }

    func loadModel() async throws {
        guard !isLoaded else { return }

        guard FileManager.default.fileExists(atPath: modelPath.path) else {
            throw LocanaraError.modelNotDownloaded(modelPath.lastPathComponent)
        }

        let fileSize = (try? FileManager.default.attributesOfItem(atPath: modelPath.path)[.size] as? Int64) ?? 0
        guard fileSize >= 10_000_000 else {
            throw LocanaraError.modelLoadFailed("Invalid model file: too small")
        }

        let numThreads = max(4, ProcessInfo.processInfo.activeProcessorCount - 2)
        let llamaParam = LlamaClient.Parameter(
            context: 8192,
            seed: nil,
            numberOfThreads: numThreads,
            batch: 512,
            temperature: 0.5,
            topK: 40,
            topP: 0.9,
            typicalP: 1.0,
            penaltyLastN: 64,
            penaltyRepeat: 1.2,
            options: LlamaClient.Options(
                extraEOSTokens: ["</s>", "<end_of_turn>"],
                verbose: false
            )
        )

        let localModel = LLMSession.LocalModel.llama(
            url: modelPath,
            mmprojURL: mmprojPath,
            parameter: llamaParam
        )
        let session = LLMSession(model: localModel)
        try await session.prewarm()
        lock.withLock {
            llmSession = session
            loaded = true
        }
        logger.info("Bridge engine loaded model: \(self.modelPath.lastPathComponent)")
    }

    func generate(prompt: String, config: InferenceConfig) async throws -> String {
        try await beginInference()
        defer { endInference() }

        guard let session = loadedSessionSnapshot() else {
            throw LocanaraError.custom(.modelNotLoaded, "Model not loaded")
        }

        do {
            var result = try await session.respond(to: prompt)

            if let stops = config.stopSequences {
                for stop in stops {
                    if let range = result.range(of: stop) {
                        result = String(result[..<range.lowerBound])
                        break
                    }
                }
            }

            let maxChars = config.maxTokens * 4
            if result.count > maxChars {
                let truncated = String(result.prefix(maxChars))
                if let period = truncated.lastIndex(of: ".") {
                    result = String(truncated[...period])
                } else {
                    result = truncated
                }
            }

            return result.trimmingCharacters(in: .whitespacesAndNewlines)
        } catch let error as NSError {
            if error.domain == "LLMSession" || error.code == -1 {
                lock.withLock { loaded = false; llmSession = nil }
            }
            throw LocanaraError.executionFailed(error.localizedDescription)
        } catch {
            throw LocanaraError.executionFailed(error.localizedDescription)
        }
    }

    func generateStreaming(prompt: String, config: InferenceConfig) -> AsyncThrowingStream<String, Error> {
        AsyncThrowingStream { continuation in
            Task { [weak self] in
                guard let self else {
                    continuation.finish(throwing: LocanaraError.custom(.modelNotLoaded, "Model not loaded"))
                    return
                }
                do {
                    try await self.beginInference()
                } catch {
                    continuation.finish(throwing: error)
                    return
                }
                guard let session = self.loadedSessionSnapshot() else {
                    self.endInference()
                    continuation.finish(throwing: LocanaraError.custom(.modelNotLoaded, "Model not loaded"))
                    return
                }
                do {
                    for try await text in session.streamResponse(to: prompt) {
                        if self.lock.withLock({ self.isCancelled }) { break }
                        continuation.yield(text)
                    }
                    self.endInference()
                    continuation.finish()
                } catch {
                    self.endInference()
                    continuation.finish(throwing: LocanaraError.executionFailed(error.localizedDescription))
                }
            }
        }
    }

    func generateWithImage(prompt: String, imageData: Data, config: InferenceConfig) async throws -> String {
        guard isMultimodal else {
            throw LocanaraError.custom(.featureNotSupported, "mmproj file required for image input")
        }
        try await beginInference()
        defer { endInference() }

        guard let session = loadedSessionSnapshot() else {
            throw LocanaraError.custom(.modelNotLoaded, "Model not loaded")
        }

        #if os(iOS)
        guard let image = UIImage(data: imageData) else {
            throw LocanaraError.custom(.invalidInput, "Failed to create image from data")
        }
        let attachment = LLMAttachment.image(image)
        let response = try await session.respond(to: prompt, attachments: [attachment])
        return response.trimmingCharacters(in: .whitespacesAndNewlines)
        #else
        throw LocanaraError.custom(.featureNotSupported, "Image input not supported on this platform")
        #endif
    }

    func cancel() -> Bool {
        lock.lock()
        defer { lock.unlock() }
        if !isCancelled { isCancelled = true; return true }
        return false
    }

    func unload() {
        lock.lock()
        llmSession = nil
        loaded = false
        isInferencing = false
        lock.unlock()
        logger.info("Bridge engine unloaded")
    }
}

// MARK: - Bridge Provider (@objc discoverable by Locanara SDK)

@objc
@available(iOS 17.0, *)
public class LlamaCppBridgeEngine: NSObject, LlamaCppPreparedBridgeProvider {

    private var preparedEngine: BridgedLlamaCppEngine?
    private var committedEngine: BridgedLlamaCppEngine?
    private var isPreparing = false
    private var prepareGeneration: UInt64 = 0
    private let stateLock = NSLock()

    public var isModelLoaded: Bool {
        stateLock.withLock { committedEngine?.isLoaded ?? false }
    }

    public func loadAndRegisterModel(_ modelPath: String, mmprojPath: String?, completion: @escaping (NSError?) -> Void) {
        prepareModel(modelPath, mmprojPath: mmprojPath) { [weak self] error in
            if let error {
                completion(error)
                return
            }

            guard let self else {
                completion(NSError(domain: "LlamaCppBridge", code: -3, userInfo: [NSLocalizedDescriptionKey: "Bridge provider was released during model load"]))
                return
            }

            do {
                try self.commitPreparedModel()
                completion(nil)
            } catch {
                completion(error as NSError)
            }
        }
    }

    public func prepareModel(_ modelPath: String, mmprojPath: String?, completion: @escaping (NSError?) -> Void) {
        let generation: UInt64
        let displacedEngine: BridgedLlamaCppEngine?

        stateLock.lock()
        guard !isPreparing else {
            stateLock.unlock()
            completion(NSError(domain: "LlamaCppBridge", code: -1, userInfo: [NSLocalizedDescriptionKey: "Model preparation already in progress"]))
            return
        }
        isPreparing = true
        prepareGeneration &+= 1
        generation = prepareGeneration
        displacedEngine = preparedEngine
        preparedEngine = nil
        stateLock.unlock()

        displacedEngine?.unload()

        Task {
            do {
                let modelURL = URL(fileURLWithPath: modelPath)
                let mmprojURL = mmprojPath.map { URL(fileURLWithPath: $0) }

                let newEngine = BridgedLlamaCppEngine(modelPath: modelURL, mmprojPath: mmprojURL)
                try await newEngine.loadModel()

                let accepted = self.stateLock.withLock {
                    guard self.isPreparing, self.prepareGeneration == generation else {
                        return false
                    }
                    self.preparedEngine = newEngine
                    self.isPreparing = false
                    return true
                }

                if accepted {
                    logger.info("Bridge: model prepared")
                    completion(nil)
                } else {
                    newEngine.unload()
                    completion(NSError(domain: "LlamaCppBridge", code: -2, userInfo: [NSLocalizedDescriptionKey: "Model preparation was discarded"]))
                }
            } catch {
                self.stateLock.withLock {
                    if self.prepareGeneration == generation {
                        self.isPreparing = false
                    }
                }
                logger.error("Bridge: prepareModel failed: \(error.localizedDescription)")
                completion(error as NSError)
            }
        }
    }

    public func commitPreparedModel() throws {
        stateLock.lock()
        defer { stateLock.unlock() }

        guard !isPreparing, let nextEngine = preparedEngine else {
            throw NSError(domain: "LlamaCppBridge", code: -4, userInfo: [NSLocalizedDescriptionKey: "No prepared model is available to commit"])
        }

        if let oldEngine = committedEngine {
            InferenceRouter.shared.unregisterEngine()
            oldEngine.unload()
        }

        preparedEngine = nil
        committedEngine = nextEngine
        InferenceRouter.shared.registerEngine(nextEngine as any InferenceEngine)
        logger.info("Bridge: prepared model committed and engine registered")
    }

    public func discardPreparedModel() {
        let engineToDiscard = stateLock.withLock {
            prepareGeneration &+= 1
            isPreparing = false
            let engine = preparedEngine
            preparedEngine = nil
            return engine
        }

        engineToDiscard?.unload()
        logger.info("Bridge: prepared model discarded")
    }

    public func unloadModel() {
        let discardedEngine: BridgedLlamaCppEngine?

        stateLock.lock()
        prepareGeneration &+= 1
        isPreparing = false
        discardedEngine = preparedEngine
        preparedEngine = nil

        if let engine = committedEngine {
            InferenceRouter.shared.unregisterEngine()
            engine.unload()
            committedEngine = nil
            logger.info("Bridge: committed model unloaded and engine unregistered")
        }
        stateLock.unlock()

        discardedEngine?.unload()
    }
}
